version: 2.1

jobs:
  # for arm, we only have ubuntu, so we use that everywhere
  build:
    parameters:
      rclass:
        description: resource_class to use
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: << parameters.rclass >>
    working_directory: /tmp/workspace
    steps:
      - run:
          name: Install dependencies (on master, install varnish from source)
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export DEBCONF_NONINTERACTIVE_SEEN=true
            curl -s https://packagecloud.io/install/repositories/varnishcache/varnish71/script.deb.sh | sudo bash
            sudo -E -- apt-get install -y \
                automake \
                make \
                python3-docutils \
                python3 \
                python3-sphinx \
                varnish-dev
      - checkout
      - run:
          name: Build and test
          command: |
            ./bootstrap
            ./configure
            make -k
            make check -j4 VERBOSE=1
            sudo make install


# two workflows, identical but for their triggers (commit/scheduled)
workflows:
  version: 2
  # run the build job for all commits
  commit: &jobs
    jobs:
      - build:
          name: x64
          rclass: medium
      - build:
          name: aarch64
          rclass: arm.medium
  # every week, run build too, in case packages got updated
  nightly:
    <<: *jobs
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
